### ISSUE TITLE
Need more full example how to use with ItsMe App

### ISSUE THREAD

**Issue by tangkhaiphuong** [MatthiasKunnen/node-itsme-client#1]

**Comment by MatthiasKunnen** [comment]
I'm not quite sure what you're referring to. What is OntDesk?

**Comment by tangkhaiphuong** [comment]
@MatthiasKunnen It just ItsMe https://www.itsme.be/

**Comment by MatthiasKunnen** [comment]
What kind of examples do you expect?
There already is https://github.com/MatthiasKunnen/node-itsme-client/blob/master/README.md where the usage of all public methods are detailed and https://github.com/MatthiasKunnen/node-itsme-client/blob/master/RESPONSES.md which shows responses in detail.
